#!/usr/bin/env bash 
#
if [ -e "school" ]; then
    echo "school file exists"

    # boş olub-olmadığını yoxla
    if [ ! -s "school" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    # regular file olub-olmadığını yoxla
    if [ -f "school" ]; then
        echo "school is a regular file"
    fi

else
    echo "school file does not exist"
fi
